package auth

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// AuthOKCode is the HTTP code returned for type AuthOK
const AuthOKCode int = 200

/*AuthOK successful operation

swagger:response authOK
*/
type AuthOK struct {

	/*
	  In: Body
	*/
	Payload string `json:"body,omitempty"`
}

// NewAuthOK creates AuthOK with default headers values
func NewAuthOK() *AuthOK {
	return &AuthOK{}
}

// WithPayload adds the payload to the auth o k response
func (o *AuthOK) WithPayload(payload string) *AuthOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the auth o k response
func (o *AuthOK) SetPayload(payload string) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *AuthOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}

}

// AuthBadRequestCode is the HTTP code returned for type AuthBadRequest
const AuthBadRequestCode int = 400

/*AuthBadRequest Invalid status value

swagger:response authBadRequest
*/
type AuthBadRequest struct {
}

// NewAuthBadRequest creates AuthBadRequest with default headers values
func NewAuthBadRequest() *AuthBadRequest {
	return &AuthBadRequest{}
}

// WriteResponse to the client
func (o *AuthBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
}

// AuthForbiddenCode is the HTTP code returned for type AuthForbidden
const AuthForbiddenCode int = 403

/*AuthForbidden Access denied

swagger:response authForbidden
*/
type AuthForbidden struct {
}

// NewAuthForbidden creates AuthForbidden with default headers values
func NewAuthForbidden() *AuthForbidden {
	return &AuthForbidden{}
}

// WriteResponse to the client
func (o *AuthForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(403)
}

// AuthInternalServerErrorCode is the HTTP code returned for type AuthInternalServerError
const AuthInternalServerErrorCode int = 500

/*AuthInternalServerError Operation error

swagger:response authInternalServerError
*/
type AuthInternalServerError struct {
}

// NewAuthInternalServerError creates AuthInternalServerError with default headers values
func NewAuthInternalServerError() *AuthInternalServerError {
	return &AuthInternalServerError{}
}

// WriteResponse to the client
func (o *AuthInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
}
