package restapi

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
)

// SwaggerJSON embedded version of the swagger document used at generation time
var SwaggerJSON json.RawMessage

func init() {
	SwaggerJSON = json.RawMessage([]byte(`{
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "description": "This is a simple auth service",
    "title": "testauth",
    "contact": {
      "email": "onokonem@gmail.com"
    },
    "license": {
      "name": "MIT"
    },
    "version": "0.0.1"
  },
  "host": "localhost:8080",
  "basePath": "/testauth",
  "paths": {
    "/auth": {
      "get": {
        "description": "YAML-based definitions suck again",
        "produces": [
          "application/json"
        ],
        "tags": [
          "auth"
        ],
        "summary": "Yes we can!",
        "operationId": "auth",
        "parameters": [
          {
            "type": "string",
            "description": "Login",
            "name": "login",
            "in": "query",
            "required": true
          },
          {
            "type": "string",
            "description": "Password",
            "name": "password",
            "in": "query",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "successful operation",
            "schema": {
              "type": "string"
            }
          },
          "400": {
            "description": "Invalid status value"
          },
          "403": {
            "description": "Access denied"
          },
          "500": {
            "description": "Operation error"
          }
        }
      }
    }
  },
  "tags": [
    {
      "description": "OMG NOT AGAIN!",
      "name": "ping"
    }
  ]
}`))
}
